site_name: Hadron
pages:
    - What is Hadron: index.md
    # - The technological benefits of Hadron: benefits.md
    - Hadron core: core.md
    # - Good reason to use Hadron: reasons.md
    - Routing: routing.md
    - Validation: validation.md
    - Serialization: serialization.md
    - JSON Provider: json-provider.md
    - TypeORM: typeorm.md
    - Events: events.md
    - How to test with Hadron: tests.md
    # - CRUD example app: example.md
    # - CLI Console: cli.md
    # - Customize: customize.md
    # - Docker: docker.md
theme: readthedocs
# docs_dir: /documents/src
docs_dir: src
