site_name: Hadron.pro
pages:
    - TypeORM: typeorm.md
    - Routing: routing.md
    - What is Hadron: index.md
    - Good reason to use Hadron: reasons.md
    - The technological benefits of Hadron: benefits.md
    - Docker: docker.md
    - How to test with Hadron: tests.md
    - CRUD example app: example.md
    - Customize: customize.md
    - Dependency Injection: di.md
    - CLI Console: cli.md
    - Events: events.md
    - Validation: validation.md
    - JSON Provider: json-provider.md
 
 
theme: readthedocs
# docs_dir: /documents/src
docs_dir: src
